// English glosses for the lyric lines (used as small editorial subtitles).
export const GLOSS = {
  'ロザリオ 巻きつけたネック': 'a rosary wound around the neck',
  '聖歌がゆがんで始まる': 'the hymn begins — distorted',
  'ひょうたんに月をひとつ': 'one moon, caught in a gourd',
  '彼女は笑って歌い出す': 'she laughs, and starts to sing',
  'ベースが下を這うように': 'the bass crawls along beneath',
  '祈りの言葉のように': 'like the words of a prayer',
  '揺れる玉響 高鳴る鼓動': 'a trembling tamayura · a racing heart',
  '五つの名前が ひとつの音になる': 'five names become one sound',
  'さあ カミナレ': 'come on — kaminare · resound, gods',
  '空までゆがませて': 'bend it all the way up to the sky',
  '誰の神だって構わない': "it doesn't matter whose god",
  'サビでは宗派も要らない': 'no sect is needed in the chorus',
  '少女の声がヤイバになって': "a girl's voice becomes a blade",
  '沈黙を切り裂いて': 'cutting the silence apart',
  '私たちが私たちの神': 'we are our own gods',
  'さあ さあ': 'come on · come on',
  '四拍子の中 誰もが平等': 'inside four-four time, everyone is equal',
  'スティックは八芒星': 'the sticks trace eight-pointed stars',
  'ツーバスで夜を砕いて': 'twin kick drums smash the night',
  'リードは白い鳩になって': 'the lead line becomes a white dove',
  '祭壇から音の壁へ': 'from the altar to the wall of sound',
  'お経と弦を鳴らして': 'ringing out sutras and strings',
  '同じ振動を信じてる': 'we believe in the same vibration',
  '違う名前 違う祈り': 'different names · different prayers',
  '同じサビで出会う': 'meeting in the same chorus',
  '誰も頭を下げなくていい': 'nobody has to bow their head',
  '弦はすべての信心を知ってる': 'the strings know every kind of faith',
  'もし明日 声を殺せと言われても': 'even if tomorrow they tell us to kill our voices',
  '笑い声も 音量も': 'our laughter, our volume —',
  '教会ごと 神殿ごと': 'whole churches, whole shrines',
  '丸ごとステージに乗せてやる': "we'll haul it all up onto the stage",
  'この拍の上 誰もが平等': 'on top of this beat, everyone is equal',
  '最後の音符が落ちて': 'the last note falls',
  '鐘の余韻だけが残る': "only the bell's echo remains",
};
export const gloss = (line) => GLOSS[line.text] || '';
