"""Lay the narration lines out on one clock and write src/data/timeline.js + narration.wav.
usage: python3 tools/build_timeline.py <voice-workdir>"""
import json, os, sys, subprocess
import numpy as np, soundfile as sf
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
work = sys.argv[1]
S = json.load(open(os.path.join(root, 'tools', 'script.json')))
L = json.load(open(os.path.join(work, 'lines.json')))
SR = 48000
START, GAP, SCENE_GAP, TAIL = 4.2, 0.34, 1.5, 7.0
EXTRA = {('five', 0): 0.5, ('gbe', 2): 0.9, ('gbe', 5): 0.6, ('axes', 5): 0.5, ('meteor', 1): 0.5, ('tools', 1): 0.5, ('flux', 2): 0.4, ('end', 0): 0.5}
t = START
scenes, clips = [], []
k = 0
for si, sc in enumerate(S['scenes']):
    if si: t += SCENE_GAP
    sd = {'id': sc['id'], 't0': round(t - (SCENE_GAP * 0.5 if si else START), 3), 'lines': []}
    for li, ln in enumerate(sc['lines']):
        rec = L[k]; k += 1
        assert rec['scene'] == sc['id'] and rec['li'] == li
        words = [{'t': round(t + w['t'], 3), 'w': w['w']} for w in rec['words']]
        sd['lines'].append({'t0': round(t, 3), 't1': round(t + rec['dur'], 3), 'show': ln['show'], 'say': ln['say'], 'words': words})
        clips.append((t, rec['file']))
        t += rec['dur'] + GAP + EXTRA.get((sc['id'], li), 0)
    scenes.append(sd)
total = t + TAIL
for i, s in enumerate(scenes):
    s['t1'] = round(scenes[i + 1]['t0'] if i + 1 < len(scenes) else total, 3)
# narration track
mix = np.zeros(int(total * SR) + SR, dtype=np.float32)
for t0, f in clips:
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-i', f, '-f', 'f32le', '-ac', '1', '-ar', str(SR), '-'], capture_output=True).stdout
    a = np.frombuffer(raw, dtype=np.float32)
    i0 = int(t0 * SR)
    mix[i0:i0 + len(a)] += a
sf.write(os.path.join(work, 'narration.wav'), mix, SR)
js = '// Generated by tools/build_timeline.py — narration clock (seconds)\nexport const TOTAL = %.3f;\nexport const SCENES = %s;\n' % (total, json.dumps(scenes, ensure_ascii=False))
open(os.path.join(root, 'src', 'data', 'timeline.js'), 'w').write(js)
print('total', round(total, 2))
for s in scenes: print(f"{s['id']:9s} {s['t0']:7.2f} {s['t1']:7.2f}")
