"""Re-encode the downloaded textures/photos and embed them as data URIs in assets/textures.js
(WebGL may not read image files from file://, so images travel inside a script).
usage: python3 tools/build_textures.py <dir-with-downloads>"""
import sys, os, io, base64
from PIL import Image
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = sys.argv[1]
JOBS = {  # key: (file, max_w, quality, grayscale)
    'earth': ('2k_earth_daymap.jpg', 2048, 84, False),
    'earthNight': ('2k_earth_nightmap.jpg', 2048, 78, False),
    'clouds': ('2k_earth_clouds.jpg', 2048, 76, True),
    'mars': ('2k_mars.jpg', 2048, 82, False),
    'jupiter': ('2k_jupiter.jpg', 2048, 82, False),
    'moon': ('2k_moon.jpg', 1024, 80, False),
    'tycho': ('tycho.jpg', 1100, 86, False),
}
lines = ['// Generated by tools/build_textures.py — see assets/LICENSES.md for credits', 'window.EXPLAINER_TEX = {']
tot = 0
for k, (fn, mw, q, g) in JOBS.items():
    im = Image.open(os.path.join(src, fn)).convert('L' if g else 'RGB')
    if im.width > mw:
        im = im.resize((mw, round(im.height * mw / im.width)), Image.LANCZOS)
    b = io.BytesIO()
    im.save(b, 'JPEG', quality=q, optimize=True, progressive=True)
    d = b.getvalue()
    tot += len(d)
    lines.append(f'  "{k}": "data:image/jpeg;base64,{base64.b64encode(d).decode()}",')
    print(k, im.size, len(d))
lines.append('};')
open(os.path.join(root, 'assets', 'textures.js'), 'w').write('\n'.join(lines) + '\n')
print('total', tot)
