"""Instance + subset the fonts to the glyphs used, emit assets/fonts.js (base64 WOFF2).
usage: python3 tools/build_fonts.py <dir-with-ttf>"""
import sys, os, re, base64, glob, io, json
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = sys.argv[1]
chars = set(chr(c) for c in range(0x20, 0x7f))
for f in glob.glob(os.path.join(root, 'src', '**', '*.js'), recursive=True) + [os.path.join(root, 'index.html'), os.path.join(root, 'tools', 'script.json')]:
    chars |= set(open(f, encoding='utf8').read())
chars |= set('⁰¹²³⁴⁵⁶⁷⁸⁹⁻×·—–≈≥≤≪≫→←↑↓√∞°±%‰。，、：；！？（）「」《》“”‘’…')
chars = {c for c in chars if c.isprintable() or c == ' '}
text = ''.join(sorted(chars))
FONTS = {  # family: (file, wght)
    'KSans': ('NotoSansSC[wght].ttf', 400),
    'KSansM': ('NotoSansSC[wght].ttf', 500),
    'KSansB': ('NotoSansSC[wght].ttf', 700),
    'KSerif': ('NotoSerifSC[wght].ttf', 600),
    'KSerifH': ('NotoSerifSC[wght].ttf', 900),
    'KMono': ('JetBrainsMono[wght].ttf', 500),
    'KMonoB': ('JetBrainsMono[wght].ttf', 750),
    'KGro': ('SpaceGrotesk[wght].ttf', 600),
}
out = ['// Generated by tools/build_fonts.py — subset WOFF2 fonts (SIL OFL 1.1, see assets/LICENSES.md)', 'window.EXPLAINER_FONTS = {']
total = 0
for fam, (fn, w) in FONTS.items():
    font = TTFont(os.path.join(src, fn))
    font = instancer.instantiateVariableFont(font, {'wght': w})
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['*']
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(text=text)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = 'woff2'
    font.save(buf)
    b = buf.getvalue()
    total += len(b)
    out.append(f'  "{fam}": "{base64.b64encode(b).decode()}",')
    print(fam, len(b))
out.append('};')
open(os.path.join(root, 'assets', 'fonts.js'), 'w').write('\n'.join(out) + '\n')
print('glyphs', len(text), 'bytes', total)
