"""Subset the display fonts to exactly the glyphs the PV uses and emit assets/fonts.js
(base64 WOFF2 so they load from file:// as well as from any host).
usage: python3 tools/build_fonts.py <dir-with-ttf>"""
import sys, os, re, base64, glob, io
from fontTools import subset
from fontTools.ttLib import TTFont

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = sys.argv[1]
chars = set(chr(c) for c in range(0x20, 0x7f))
for f in glob.glob(os.path.join(root, 'src', '**', '*.js'), recursive=True) + [os.path.join(root, 'index.html')]:
    if 'audio-data' in f:
        # lyric text only
        t = open(f, encoding='utf8').read()
        chars |= set(''.join(re.findall(r'"text": ?"([^"]*)"', t)))
        continue
    chars |= set(open(f, encoding='utf8').read())
chars = {c for c in chars if c.isprintable() or c == ' '}
chars |= set('、。「」『』・…―ー！？（）〜♪♩')
text = ''.join(sorted(chars))
FONTS = {
    'KMincho': 'ZenOldMincho-Black.ttf',
    'KMinchoB': 'ZenOldMincho-Bold.ttf',
    'KGothic': 'DelaGothicOne-Regular.ttf',
    'KBrush': 'YujiBoku-Regular.ttf',
    'KSyuku': 'YujiSyuku-Regular.ttf',
    'KBlack': 'UnifrakturMaguntia-Book.ttf',
    'KSerif': 'CormorantGaramond[wght].ttf',
    'KMono': 'IBMPlexMono-Regular.ttf',
    'KDot': 'DotGothic16-Regular.ttf',
}
out = ['// Generated by tools/build_fonts.py — subset WOFF2 fonts (SIL OFL 1.1, see assets/LICENSES.md)', 'window.KAMINARE_FONTS = {']
total = 0
for fam, fn in FONTS.items():
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['*']
    opts.name_IDs = ['*']
    opts.notdef_outline = True
    font = TTFont(os.path.join(src, fn))
    sub = subset.Subsetter(opts)
    sub.populate(text=text)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = 'woff2'
    font.save(buf)
    b = buf.getvalue()
    total += len(b)
    out.append(f'  "{fam}": "{base64.b64encode(b).decode()}",')
    print(fam, len(b))
out.append('};')
open(os.path.join(root, 'assets', 'fonts.js'), 'w').write('\n'.join(out) + '\n')
print('glyphs', len(text), 'bytes', total)
