import librosa, numpy as np, json, base64
SR=22050; FPS=60; HOP=SR//FPS  # 367.5 -> use float frames via resample
mix,_=librosa.load('src/song.wav',sr=SR,mono=True)
inst,_=librosa.load('sep/htdemucs/song/no_vocals.wav',sr=SR,mono=True)
voc,_=librosa.load('sep/htdemucs/song/vocals.wav',sr=SR,mono=True)
dur=len(mix)/SR; N=int(dur*FPS)+1
hop=256
def stft(y): return np.abs(librosa.stft(y,n_fft=2048,hop_length=hop))
Si=stft(inst); Sm=stft(mix); Sv=stft(voc)
f=librosa.fft_frequencies(sr=SR,n_fft=2048); t=librosa.frames_to_time(np.arange(Si.shape[1]),sr=SR,hop_length=hop)
def band(S,lo,hi): return S[(f>=lo)&(f<hi)].sum(0)
def flux(x): lx=np.log1p(x*10); d=np.diff(lx,prepend=lx[0]); return np.maximum(d,0)
def tofps(x):
    tt=np.arange(N)/FPS
    return np.interp(tt,t,x)
def env(x,att=0.0,rel=0.12):
    # peak-hold with exponential release at FPS
    out=np.zeros_like(x); a=np.exp(-1/(rel*FPS)); v=0
    for i,xi in enumerate(x):
        v=max(xi,v*a); out[i]=v
    return out
def norm(x,p=99): s=np.percentile(x,p); return np.clip(x/(s+1e-9),0,1)
kick=env(tofps(norm(flux(band(Si,30,110)))) ,rel=0.10)
snare=env(tofps(norm(flux(band(Si,1500,5000)+band(Si,180,350)*0.5))),rel=0.10)
hat=norm(tofps(np.log1p(band(Si,7000,11000))),99.5)
bass=norm(tofps(np.log1p(band(Si,40,220))),99.5)
vocal=norm(tofps(np.log1p(band(Sv,200,4000))),99.5)
loud=norm(tofps(librosa.feature.rms(y=mix,frame_length=2048,hop_length=hop)[0]),99.5)
def smooth(x,k=5): return np.convolve(x,np.ones(k)/k,mode='same')
chans=[kick,snare,smooth(hat,3),smooth(bass,5),smooth(vocal,4),smooth(loud,6)]
for c in chans: print(np.round(np.percentile(c,[10,50,90,99]),2))
b=bytes(np.clip(np.stack(chans,1)*255,0,255).astype(np.uint8).flatten())
# onset events
def events(x,thr):
    xs=tofps(x); pk=librosa.util.peak_pick(xs,pre_max=6,post_max=6,pre_avg=10,post_avg=10,delta=thr,wait=8)
    return [round(i/FPS,3) for i in pk]
kev=events(norm(flux(band(Si,30,110))),0.12)
sev=events(norm(flux(band(Si,1500,5000))),0.10)
print(len(kev),len(sev))
P=60/172; O=0.0638
lyr=json.load(open('lyrics_aligned.json'))
for l in lyr:
    if l['text'].startswith('この拍'): l['c'][0]=158.22
js=f"""// Generated by tools/export.py — audio analysis of the song (do not edit by hand)
export const DURATION = {dur:.3f};
export const BPM = 172;
export const BEAT = {P:.6f};
export const OFFSET = {O};
export const FPS = {FPS};
export const NCH = {len(chans)};
// channels: 0 kick, 1 snare, 2 hats, 3 bass, 4 vocal, 5 loudness (uint8, interleaved)
export const ENV_B64 = "{base64.b64encode(b).decode()}";
export const KICKS = {json.dumps(kev)};
export const SNARES = {json.dumps(sev)};
export const LYRICS = {json.dumps(lyr,ensure_ascii=False)};
"""
open('/home/user/test/kaminare-pv/src/data/audio-data.js','w').write(js)
print(len(js))
