export const FAMILIES = [
  {
    id: 0,
    key: 'gpt',
    name: 'GPT',
    maker: 'OpenAI',
    snapshot: 'GPT-6.1 Sol / GPT-Live voice',
    palette: { base: '#167d79', light: '#b7e2d3', dark: '#103b43', accent: '#e4bf79', ink: '#e9f4e8' },
    pattern: 'orbit',
    world: 'The Relay Garden',
    worldLine: 'A small observatory where thought paths braid, split, and return.',
    abilities: [
      { name: 'Deliberate reasoning', zh: '深推演', detail: 'Allocates extra inference to difficult, multi-step problems; the cell’s paired loops slowly converge.', glyph: 'converge', tempo: 0.54 },
      { name: 'Image–text synthesis', zh: '图文合成', detail: 'Combines text and image input into one response; both signals meet at a shared node.', glyph: 'triad', tempo: 0.72 },
      { name: 'Repository-scale coding', zh: '仓库级编程', detail: 'Reads, edits, tests, and iterates over software projects rather than stopping at a snippet.', glyph: 'brackets', tempo: 0.84 },
      { name: 'Computer use', zh: '屏幕操作', detail: 'Plans and performs browser or desktop actions, then checks the changed screen state.', glyph: 'cursor', tempo: 0.66 },
      { name: 'Parallel delegation', zh: '并行委派', detail: 'Splits independent work among coordinated agents and gathers their results.', glyph: 'branch', tempo: 0.62 },
      { name: 'Grounded web research', zh: '联网溯源', detail: 'Searches for evidence and returns source-linked findings instead of treating memory as a citation.', glyph: 'lens', tempo: 0.48 },
      { name: 'Low-latency voice', zh: '实时语音', detail: 'A companion GPT-Live voice model handles natural audio turn-taking; it is a separate voice branch, not an audio-input claim for GPT-6.1 Sol.', glyph: 'wave', tempo: 0.9 },
      { name: 'Structured contracts', zh: '结构化输出', detail: 'Follows schemas and produces machine-readable outputs for downstream tools.', glyph: 'schema', tempo: 0.58 },
      { name: 'Long-run continuity', zh: '长程连续性', detail: 'Retains useful state across extended workflows and context-window compaction.', glyph: 'memory', tempo: 0.43 },
    ],
  },
  {
    id: 1,
    key: 'claude',
    name: 'Claude',
    maker: 'Anthropic',
    snapshot: 'Claude 5.5 family',
    palette: { base: '#b66f4d', light: '#f0d2aa', dark: '#563b39', accent: '#e4bd73', ink: '#fff1db' },
    pattern: 'folio',
    world: 'The Quiet Archive',
    worldLine: 'Paper-like terraces collect notes, then send selected pages onward.',
    abilities: [
      { name: 'Extended thinking', zh: '延展思考', detail: 'Uses adjustable effort to spend more or less time on a task; page-like traces open in stages.', glyph: 'pages', tempo: 0.39 },
      { name: 'Codebase navigation', zh: '代码脉络', detail: 'Tracks relationships across files and sustains edits through larger engineering tasks.', glyph: 'route', tempo: 0.65 },
      { name: 'Desktop interaction', zh: '桌面交互', detail: 'Reads a visual interface and carries out computer-use steps with feedback.', glyph: 'window', tempo: 0.73 },
      { name: 'Document-long context', zh: '长文档理解', detail: 'Works across lengthy source material while preserving references and local detail.', glyph: 'bookmark', tempo: 0.45 },
      { name: 'Editorial voice', zh: '文风校准', detail: 'Revises tone, structure, and phrasing while keeping the intended meaning intact.', glyph: 'quill', tempo: 0.51 },
      { name: 'Artifacts and prototypes', zh: '可交付原型', detail: 'Claude’s app Artifacts can turn an exchange into a self-contained document, visual, or runnable interface; this is a product feature.', glyph: 'artifact', tempo: 0.77 },
      { name: 'Tool interoperability', zh: '工具互联', detail: 'Connects to external tools and services through APIs and the Model Context Protocol.', glyph: 'plug', tempo: 0.69 },
      { name: 'Constitutional steering', zh: '原则约束', detail: 'References Anthropic’s research lineage using explicit behavioral principles; the exact current Claude 5.5 training recipe is not public.', glyph: 'guard', tempo: 0.36 },
      { name: 'Research synthesis', zh: '研究综述', detail: 'Compares evidence across a source set and produces a traceable synthesis.', glyph: 'folio', tempo: 0.57 },
    ],
  },
  {
    id: 2,
    key: 'gemini',
    name: 'Gemini',
    maker: 'Google DeepMind',
    snapshot: 'Gemini 4 Argon / 3.8 family + Robotics-ER 1.6 (separate branch)',
    palette: { base: '#697cc8', light: '#d8dcff', dark: '#283856', accent: '#efbd7a', ink: '#eef0ff' },
    pattern: 'prism',
    world: 'The Spectrum Shelf',
    worldLine: 'Prismatic ledges refract incoming signals into distinct working paths.',
    abilities: [
      { name: 'Native multimodal reasoning', zh: '原生多模态推理', detail: 'Reasons across text, image, sound, video, and code as linked modalities.', glyph: 'prism', tempo: 0.74 },
      { name: 'Million-token workspace', zh: '百万级上下文', detail: 'Gemini 4 Argon lists a million-token output window; its launch announcement described a limited trusted-cyber-defender rollout.', glyph: 'horizon', tempo: 0.42 },
      { name: 'Deep Think mode', zh: '深度思考模式', detail: 'Routes especially difficult questions through a more deliberative reasoning mode.', glyph: 'deepthink', tempo: 0.31 },
      { name: 'Source-grounded discovery', zh: '搜索证据联结', detail: 'Connects model responses to Google Search and product knowledge surfaces.', glyph: 'search', tempo: 0.61 },
      { name: 'Live speech dialogue', zh: '实时语音对话', detail: 'Supports expressive, natural speech-to-speech interaction and spoken turn-taking.', glyph: 'speech', tempo: 0.92 },
      { name: 'Agentic software building', zh: '代理式开发', detail: 'Plans, writes, runs, and revises code through a connected development workflow.', glyph: 'build', tempo: 0.79 },
      { name: 'Connected-app actions', zh: '应用生态协作', detail: 'Uses connected Google services and app context as part of a task workflow.', glyph: 'constellation', tempo: 0.68 },
      { name: 'Spatial scene reading', zh: '空间场景理解', detail: 'Gemini Robotics-ER 1.6 is a separate embodied-reasoning branch with spatial-understanding claims; do not generalize this to the general Gemini endpoint.', glyph: 'spatial', tempo: 0.55 },
      { name: 'Visual creation and edit', zh: '图像生成与编辑', detail: 'Creates or revises imagery from instructions while following local composition cues.', glyph: 'edit', tempo: 0.7 },
    ],
  },
  {
    id: 3,
    key: 'deepseek',
    name: 'DeepSeek',
    maker: 'DeepSeek',
    snapshot: 'DeepSeek V4.1 Flash',
    palette: { base: '#2786a0', light: '#b8e9e6', dark: '#173a50', accent: '#e8bd77', ink: '#e5f8f5' },
    pattern: 'current',
    world: 'The Blue Current',
    worldLine: 'A quiet tidal basin turns small reasoning pulses into deeper currents.',
    abilities: [
      { name: 'Thinking / direct mode', zh: '思考与直答切换', detail: 'Offers a choice between deliberate reasoning and a faster direct response.', glyph: 'switch', tempo: 0.49 },
      { name: 'Mathematical problem solving', zh: '数学推演', detail: 'Works through formal, symbolic, and multi-stage quantitative questions.', glyph: 'proof', tempo: 0.35 },
      { name: 'Code-generation efficiency', zh: '高效代码生成', detail: 'A sparse mixture-of-experts design reduces active compute; the model-card coding results are vendor-reported, not a controlled cross-provider speed comparison.', glyph: 'forge', tempo: 0.82 },
      { name: 'Visual token understanding', zh: '视觉信息解析', detail: 'Reads native image and text input; video is not listed as a V4.1-Flash input modality in its model card.', glyph: 'visual', tempo: 0.71 },
      { name: 'Tool-directed execution', zh: '工具驱动执行', detail: 'Connects reasoning to tool calls and environment feedback in agent tasks.', glyph: 'toolpath', tempo: 0.63 },
      { name: 'Sparse expert routing', zh: '稀疏专家路由', detail: 'Routes tokens through a mixture-of-experts architecture to reduce active work.', glyph: 'experts', tempo: 0.57 },
      { name: 'Compact inference memory', zh: '紧凑推理缓存', detail: 'Uses a reduced key-value cache footprint for longer or cheaper serving.', glyph: 'cache', tempo: 0.41 },
      { name: 'Open deployment path', zh: '开放部署路径', detail: 'Publishes weights and technical materials for community inference work.', glyph: 'openlock', tempo: 0.52 },
      { name: 'High-throughput Flash service', zh: '高吞吐服务', detail: 'Balances latency, throughput, and cost for frequent inference requests.', glyph: 'throughput', tempo: 0.95 },
    ],
  },
  {
    id: 4,
    key: 'qwen',
    name: 'Qwen',
    maker: 'Alibaba Qwen Team',
    snapshot: 'Qwen 3.8 family',
    palette: { base: '#769b72', light: '#d1e3b6', dark: '#334b3e', accent: '#eacb81', ink: '#eef4dc' },
    pattern: 'braid',
    world: 'The Many-Tongue Delta',
    worldLine: 'Forking channels carry little lights between scripts, samples, and tools.',
    abilities: [
      { name: 'Broad multilingual translation', zh: '多语互译', detail: 'Maps meaning across languages and regional varieties rather than word-for-word substitution.', glyph: 'translate', tempo: 0.59 },
      { name: 'Document and chart reading', zh: '文档图表读取', detail: 'Extracts structure from dense pages, charts, screenshots, and visual documents.', glyph: 'document', tempo: 0.67 },
      { name: 'Speech recognition and alignment', zh: '语音识别与对齐', detail: 'Transcribes speech and aligns spoken segments to their text and timing.', glyph: 'listen', tempo: 0.88 },
      { name: 'Audio-video understanding', zh: '视听联合理解', detail: 'The separate Qwen3.8-Omni-Flash branch is described as reasoning across synchronized sound, images, and video; its announcement was marked draft.', glyph: 'av', tempo: 0.76 },
      { name: 'Agentic coding', zh: '代理式编程', detail: 'Uses iterative code, test, preview, and repair loops to build software.', glyph: 'iterate', tempo: 0.83 },
      { name: 'MCP and tool calling', zh: '工具调用协议', detail: 'Connects a model to reusable tools and external context providers.', glyph: 'call', tempo: 0.64 },
      { name: 'Context extension', zh: '上下文延展', detail: 'Extends the usable working window for very long tasks and source bundles.', glyph: 'extend', tempo: 0.44 },
      { name: 'Local open-weight use', zh: '本地开放权重', detail: 'Makes downloadable weights available for local and self-hosted deployment.', glyph: 'weights', tempo: 0.53 },
      { name: 'Long-horizon office work', zh: '长程办公任务', detail: 'Carries multi-day research or office goals through planning and repeated checks.', glyph: 'horizonwork', tempo: 0.38 },
    ],
  },
  {
    id: 5,
    key: 'glm',
    name: 'GLM',
    maker: 'Z.ai',
    snapshot: 'GLM-5.3-Flash',
    palette: { base: '#586f9c', light: '#c9d8ed', dark: '#27364d', accent: '#dfbd78', ink: '#edf3fb' },
    pattern: 'lattice',
    world: 'The Schema Foundry',
    worldLine: 'A restrained machine-garden checks its own outputs before releasing them.',
    abilities: [
      { name: 'Cross-format perception', zh: '跨格式感知', detail: 'Reads images, video, files, and interface state as part of a single workflow.', glyph: 'formats', tempo: 0.71 },
      { name: 'Terminal problem solving', zh: '终端问题求解', detail: 'Moves from diagnosis to code changes and verified command-line outcomes.', glyph: 'terminal', tempo: 0.81 },
      { name: 'Plan–act–inspect agents', zh: '计划—执行—检查', detail: 'Decomposes goals, uses tools, inspects results, and chooses the next action.', glyph: 'loopagent', tempo: 0.62 },
      { name: 'Interface-state feedback', zh: '界面状态反馈', detail: 'Uses visual feedback from an interface to decide whether an action succeeded.', glyph: 'feedback', tempo: 0.67 },
      { name: 'Office-file production', zh: '办公文件交付', detail: 'Works with slides, spreadsheets, PDFs, and documents, including layout review.', glyph: 'files', tempo: 0.56 },
      { name: 'Long-horizon task planning', zh: '长程任务规划', detail: 'Maintains a task plan across extended, multi-stage work instead of one-shot replies.', glyph: 'plan', tempo: 0.37 },
      { name: 'Million-token context', zh: '百万令牌上下文', detail: 'Supports large context windows with cache compression for long inputs.', glyph: 'compress', tempo: 0.43 },
      { name: 'Sparse-linear attention', zh: '稀疏线性注意力', detail: 'Combines sparse retrieval with linear attention to control long-context inference cost.', glyph: 'attention', tempo: 0.51 },
      { name: 'Self-hostable weights', zh: '可自托管权重', detail: 'Publishes model weights and inference-framework paths for independent deployment.', glyph: 'deploy', tempo: 0.58 },
    ],
  },
];

export const FAMILY_BY_KEY = Object.fromEntries(FAMILIES.map((family) => [family.key, family]));

export const FACE_LAYOUT = [
  { key: 'gpt', normal: [0, 0, 1], tangent: [0, 1, 0], worldOffset: 1.28 },
  { key: 'claude', normal: [1, 0, 0], tangent: [0, 1, 0], worldOffset: -1.18 },
  { key: 'gemini', normal: [0, 1, 0], tangent: [0, 0, -1], worldOffset: -1.15 },
  { key: 'deepseek', normal: [0, 0, -1], tangent: [0, 1, 0], worldOffset: -1.28 },
  { key: 'qwen', normal: [-1, 0, 0], tangent: [0, 1, 0], worldOffset: 1.18 },
  { key: 'glm', normal: [0, -1, 0], tangent: [0, 0, 1], worldOffset: 1.15 },
];

export const EASTER_EGGS = [
  {
    key: 'public-rivalry',
    name: 'Two paper couriers',
    detail: 'A tiny neutral handoff between the GPT and Claude routes nods to their 2026 Super Bowl advertising spat; it is a market rivalry, not a personal feud.',
  },
  {
    key: 'distillation-debate',
    name: 'The echo prism',
    detail: 'A mirrored shard on the GPT–DeepSeek route represents the public debate over model distillation. It does not assert that any allegation is independently established.',
  },
  {
    key: 'glue-pizza',
    name: 'The tiny blue plate',
    detail: 'A minuscule plate and sealed amber drop on the Gemini island recall the 2024 AI Overviews “glue on pizza” incident. The gag belongs to Search AI Overviews, not a verdict on Gemini as a whole; the prop is intentionally inedible and harmless.',
  },
];

if (FAMILIES.length !== 6 || FAMILIES.some((family) => family.abilities.length !== 9)) {
  throw new Error('The six-family / nine-cell schema is incomplete.');
}
