"""Collect the Tabler icons used in src/ (g.icon('name', ...) and ICON_EXTRA) into src/data/icons.js.
usage: python3 tools/build_icons.py   (needs `npm install` for @tabler/icons, MIT)"""
import glob, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'node_modules', '@tabler', 'icons', 'icons', 'outline')
names = set()
ICONSET = {f[:-4] for f in os.listdir(SRC)}
for f in glob.glob(os.path.join(ROOT, 'src', '**', '*.js'), recursive=True):
    s = open(f, encoding='utf-8').read()
    names |= set(re.findall(r"icon\(\s*'([a-z0-9-]+)'", s))
    names |= set(re.findall(r"ico:\s*'([a-z0-9-]+)'", s))
    # icon names kept in data arrays: any quoted token that is an icon file and is listed with ICON
    names |= {n for n in re.findall(r"'([a-z0-9-]+)'", s) if n in ICONSET}
out = {}
for n in sorted(names):
    p = os.path.join(SRC, n + '.svg')
    if not os.path.exists(p):
        print('missing icon', n)
        continue
    svg = open(p, encoding='utf-8').read()
    ds = [m.group(2) for m in re.finditer(r'<path(\s+stroke="none")?\s+d="([^"]+)"', svg) if not m.group(1)]
    out[n] = ds
js = '// Generated by tools/build_icons.py from Tabler Icons (MIT, https://tabler.io/icons).\nexport const ICONS = ' + json.dumps(out) + ';\n'
open(os.path.join(ROOT, 'src', 'data', 'icons.js'), 'w', encoding='utf-8').write(js)
print(len(out), 'icons')
