"""Subset the fonts to the glyphs this film uses and embed them as base64 WOFF2 in assets/fonts.js
(base64 so the page also works from file://, where font files cannot be fetched).
usage: python3 tools/build_fonts.py <dir with the downloaded .ttf files>

Fonts (all SIL OFL 1.1): Noto Serif SC, Noto Sans SC, LXGW WenKai, JetBrains Mono, STIX Two Text."""
import base64, glob, io, json, os, re, sys

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1]

chars = set()
S = json.load(open(os.path.join(ROOT, 'tools', 'script.json'), encoding='utf-8'))
for sc in S['scenes']:
    chars |= set(''.join(sc['title']))
    for ln in sc['lines']:
        chars |= set(ln['say']) | set(ln.get('show', ''))
for f in glob.glob(os.path.join(ROOT, 'src', '**', '*.js'), recursive=True) + [os.path.join(ROOT, 'index.html')]:
    if f.endswith('icons.js') or f.endswith('timeline.js'):
        continue
    s = open(f, encoding='utf-8').read()
    for m in re.finditer(r"'((?:[^'\\\n]|\\.)*)'|\"((?:[^\"\\\n]|\\.)*)\"|`((?:[^`\\]|\\.)*)`", s):
        chars |= set(m.group(1) or m.group(2) or m.group(3) or '')
    chars |= set(re.findall(r'[ -⯿　-鿿＀-￯]', s))
chars |= set(' 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.,:;!?%+-=*/()[]<>|~^_\'"#&@')
chars |= set('⁰¹²³⁴⁵⁶⁷⁸⁹⁻₀₁₂ℵ×÷±≈≠≤≥∞∑√∛→←↑↓·…—–“”‘’「」『』《》（）【】，。；：？！、')
text = ''.join(sorted(chars))
print(len(text), 'glyphs requested')

FONTS = [
    ('NSerif', 'NotoSerifSC.ttf', [500, 700, 900]),
    ('NSans', 'NotoSansSC.ttf', [400, 500, 700]),
    ('Kai', 'LXGWWenKai-Regular.ttf', [400]),
    ('Mono', 'JetBrainsMono.ttf', [400, 600]),
    ('Stix', 'STIXTwoText.ttf', [400, 600]),
]
out = {}
total = 0
for family, fname, weights in FONTS:
    out[family] = {}
    for wgt in weights:
        f = TTFont(os.path.join(SRC, fname))
        if 'fvar' in f:
            axes = {a.axisTag: a for a in f['fvar'].axes}
            w = max(axes['wght'].minValue, min(axes['wght'].maxValue, wgt))
            f = instancer.instantiateVariableFont(f, {'wght': w})
        opts = subset.Options()
        opts.flavor = 'woff2'
        opts.layout_features = ['*']
        opts.name_IDs = ['*']
        opts.notdef_outline = True
        sub = subset.Subsetter(opts)
        sub.populate(text=text)
        sub.subset(f)
        buf = io.BytesIO()
        f.flavor = 'woff2'
        f.save(buf)
        b = buf.getvalue()
        total += len(b)
        out[family][str(wgt)] = base64.b64encode(b).decode()
        print(family, wgt, len(b) // 1024, 'KB')
js = '// Generated by tools/build_fonts.py: subset WOFF2 fonts (SIL OFL 1.1), base64.\nwindow.__FONTS = ' + json.dumps(out) + ';\n'
open(os.path.join(ROOT, 'assets', 'fonts.js'), 'w', encoding='utf-8').write(js)
print('total', total // 1024, 'KB')
