"""Embed the reference photographs as base64 data URIs in assets/images.js (data URIs keep
WebGL textures usable from file://). Sources live in assets/src-images/ (see assets/LICENSES.md).
usage: python3 tools/build_images.py"""
import base64, io, json, os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'src-images')
out = {}
# Bullet Cluster: drop the scale bar strip at the bottom
im = Image.open(os.path.join(SRC, 'bullet-cluster-1e0657.jpg')).convert('RGB')
im = im.crop((0, 40, 1920, 1220))
buf = io.BytesIO()
im.save(buf, 'JPEG', quality=86, optimize=True, progressive=True)
out['bullet'] = 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode()
im = Image.open(os.path.join(SRC, 'kepler-snr-1604.jpg')).convert('RGB')
buf = io.BytesIO()
im.save(buf, 'JPEG', quality=90, optimize=True, progressive=True)
out['kepler'] = 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode()
js = '// Generated by tools/build_images.py: reference photographs (public domain, see LICENSES.md).\nwindow.__IMAGES = ' + json.dumps(out) + ';\n'
open(os.path.join(ROOT, 'assets', 'images.js'), 'w').write(js)
for k, v in out.items():
    print(k, len(v) // 1024, 'KB')
