"""Lay the voiced lines out on one clock; write src/data/timeline.js and <workdir>/narration.wav.
usage: python3 tools/build_timeline.py <voice-workdir>

Each chapter opens with a title card (CHAPTER_GAP seconds before its first line). A line may
carry "pause": extra seconds of silence after it, so a visual can finish before the next line."""
import json, os, subprocess, sys, wave

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = sys.argv[1]
S = json.load(open(os.path.join(ROOT, 'tools', 'script.json'), encoding='utf-8'))
L = json.load(open(os.path.join(WORK, 'lines.json'), encoding='utf-8'))
SR = 48000
START, GAP, CHAPTER_GAP, TAIL = 5.0, 0.36, 3.4, 9.0

t = START
scenes, clips, k = [], [], 0
for si, sc in enumerate(S['scenes']):
    if si:
        t += CHAPTER_GAP
    sd = {'id': sc['id'], 'title': sc['title'], 't0': round(t - (CHAPTER_GAP if si else START), 3), 'lines': []}
    for li, ln in enumerate(sc['lines']):
        rec = L[k]
        k += 1
        assert rec['scene'] == sc['id'] and rec['li'] == li, (rec['scene'], sc['id'], li)
        words = [[round(t + w['t'], 3), w['w']] for w in rec['words']]
        sd['lines'].append({'t0': round(t, 3), 't1': round(t + rec['dur'], 3), 'say': ln['say'],
                            'show': ln.get('show', ln['say']), 'w': words})
        clips.append((t, rec['file']))
        t += rec['dur'] + GAP + ln.get('pause', 0)
    scenes.append(sd)
total = round(t + TAIL, 3)
for i, s in enumerate(scenes):
    s['t1'] = scenes[i + 1]['t0'] if i + 1 < len(scenes) else total

mix = np.zeros(int(total * SR) + SR, dtype=np.float32)
for t0, f in clips:
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-i', f, '-f', 'f32le', '-ac', '1', '-ar', str(SR), '-'],
                         capture_output=True, check=True).stdout
    a = np.frombuffer(raw, dtype=np.float32)
    i0 = int(t0 * SR)
    mix[i0:i0 + len(a)] += a
with wave.open(os.path.join(WORK, 'narration.wav'), 'wb') as w:
    w.setnchannels(1)
    w.setsampwidth(2)
    w.setframerate(SR)
    w.writeframes((np.clip(mix, -1, 1) * 32767).astype('<i2').tobytes())

os.makedirs(os.path.join(ROOT, 'src', 'data'), exist_ok=True)
js = ('// Generated by tools/build_timeline.py: narration clock in seconds.\n'
      'export const TOTAL = %s;\nexport const SCENES = %s;\n') % (total, json.dumps(scenes, ensure_ascii=False))
open(os.path.join(ROOT, 'src', 'data', 'timeline.js'), 'w', encoding='utf-8').write(js)
print('total', total)
for s in scenes:
    print(f"{s['id']:7s} {s['t0']:8.2f} {s['t1']:8.2f}  {s['t1'] - s['t0']:6.1f}s")
